### PR TITLE
modify wrapFunction to use original function toString

### PR DESCRIPTION
**Pull request by sparr**

### CODE REVIEW

**Comment by gdborton** [comment]
@sparr Could you provide me with your reason for this change? Example use case maybe?

**Comment by sparr** [comment]
The purpose of this is to re-enable the ability to put the name of a function/method into the console and get back its source.

**Comment by gdborton** [comment]
Ah, like typing `Creep.prototype.work`?  I'm not sure what happened previously with Travis, but I've rerun the build.  Could you update the linting issues?

**Comment by sparr** [comment]
I had the bad luck to upload this during the big DNS DDOS that affected github and a zillion other sites, so GH couldn't talk to Travis at the time. I'll make some changes when I can and re-commit. This is low priority right now because this functionality was ALSO later doubly-broken by some security changes in the core game. Devs have said it wasn't intentional but they aren't bringing it back yet, but now that the private server is open source I can submit a patch to them to fix it, too.

**Comment by gdborton** [comment]
@sparr poke. I've been trying to clean up the pending PRs. On this repo today, can you update the string and fix the linting issues?

```
/home/travis/build/gdborton/screeps-profiler/screeps-profiler.js
   78:7   error    'wrappedFunction' is never reassigned, use 'const' instead  prefer-const
   78:25  warning  Missing function expression name                            func-names
   78:33  error    Missing space before function parentheses                   space-before-function-paren
   99:30  warning  Missing function expression name                            func-names
   99:38  error    Missing space before function parentheses                   space-before-function-paren
  100:12  error    Strings must use singlequote                                quotes
  100:12  error    Unexpected string concatenation                             prefer-template
  106:1   error    Block must not be padded by blank lines                     padded-blocks
```

**Comment by sparr** [comment]
I haven't been playing screeps lately. Feel free to close this if you want. I'll come back to it some day, I hope.

**Comment by gdborton** [comment]
No worries. I think I've got edit ability, I can fix it up. I'm in the same
boat, I really just maintain this repo (poorly) and admin the slack
(delegated).

**Pull request merged**
